name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 0 * * 0' # every week
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
jobs:
  update-readme-with-blog:
    name: Update README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://lwarnt.github.io/feed.xml"
          max_post_count: 3
          feed_names: "GitHub Pages"
